'use client'

// import { Footer, Header, UseProvider } from '@components'
import UseProvider from '@redux/provider'
import Footer from '@components/Footer'
import './globals.css'
import type { Metadata } from 'next'
import MyHeader from '@components/MyHeader'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <UseProvider>
          <div className="flex flex-col min-h-screen">
            <MyHeader />
            <main className="mb-auto">{children}</main>
            <Footer />
          </div>
        </UseProvider>
      </body>
    </html>
  )
}
