export { FaBars } from 'react-icons/fa'
export { MdContentCopy as Copy } from 'react-icons/md'
export { MdOutlineEdit as Edit } from 'react-icons/md'
export { MdDone as Check } from 'react-icons/md'
export { MdKeyboardBackspace as Back } from 'react-icons/md'
export { GoHome as Home } from 'react-icons/go'
export { BiCheckCircle as CheckCircle } from 'react-icons/bi'
export { RxCrossCircled as Cross } from 'react-icons/rx'
export { TbSend as Send } from 'react-icons/tb'
export { RiDeleteBinLine as Bin, RiDeleteBin6Line as Bin2 } from 'react-icons/ri'
export { BsChevronCompactLeft as Left } from 'react-icons/bs'
export { BsChevronCompactRight as Right } from 'react-icons/bs'
export { RxDotFilled as Dot } from 'react-icons/rx'
export { RiAddLine as Plus } from 'react-icons/ri'
export { BiHide as Hide, BiShow as Show } from 'react-icons/bi'